var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/stats/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__605af78b._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_f6b2c2de._.js")
R.c("server/chunks/ssr/[root-of-the-server]__887388c4._.js")
R.c("server/chunks/ssr/node_modules_@opentelemetry_api_build_esm_9e986a62._.js")
R.c("server/chunks/ssr/node_modules_8a75d5d4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_5a8aef0f._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__cae73c0c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_stats_page_actions_cf2314a8.js")
R.m(38368)
module.exports=R.m(38368).exports
