var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/shopping-list/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6e561055._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_0ebdab63._.js")
R.c("server/chunks/ssr/[root-of-the-server]__887388c4._.js")
R.c("server/chunks/ssr/node_modules_@opentelemetry_api_build_esm_9e986a62._.js")
R.c("server/chunks/ssr/node_modules_8a75d5d4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_5a8aef0f._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__cae73c0c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_shopping-list_page_actions_00532752.js")
R.m(74566)
module.exports=R.m(74566).exports
